apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercicio-k8s-nginx
spec:
  selector:
    matchLabels:
      app: exercicio-k8s-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: exercicio-k8s-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80

          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-html
              readOnly: false

      volumes:
        - name: nginx-html
          configMap: 
            name: nginx-html
            items:
              - key: index.html
                path: index.html